services:
  postgres:
    image: postgres:15-alpine
    container_name: regen-marketplace-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: regen123
      POSTGRES_DB: regen_marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: regen-marketplace-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@regen.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: