#!/usr/bin/env tsx
import { promises as fs } from "fs"
import path from "path"

const ROOT = process.cwd()
const APP_DIR = path.join(ROOT, "app")
const OUTPUT = path.join(ROOT, "ROUTE_MAP.md")

type RouteEntry = {
  type: "page" | "layout" | "api" | "route"
  route: string
  file: string
}

async function exists(p: string) {
  try { await fs.access(p); return true } catch { return false }
}

async function collectRoutes(dir: string, base = ""): Promise<RouteEntry[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true })
  const res: RouteEntry[] = []
  for (const e of entries) {
    const full = path.join(dir, e.name)
    const routePath = path.posix.join(base, e.name)
    if (e.isDirectory()) {
      // Check for conventional files within directory
      const pageTsx = path.join(full, "page.tsx")
      const pageJsx = path.join(full, "page.jsx")
      const layoutTsx = path.join(full, "layout.tsx")
      const routeTs = path.join(full, "route.ts")
      const routeTsx = path.join(full, "route.tsx")
      const isApi = base.startsWith("/api") || e.name === "api"

      if (await exists(pageTsx)) res.push({ type: "page", route: `/${routePath}`, file: path.relative(ROOT, pageTsx) })
      if (await exists(pageJsx)) res.push({ type: "page", route: `/${routePath}`, file: path.relative(ROOT, pageJsx) })
      if (await exists(layoutTsx)) res.push({ type: "layout", route: `/${routePath}`, file: path.relative(ROOT, layoutTsx) })
      if (await exists(routeTs)) res.push({ type: isApi ? "api" : "route", route: `/${routePath}`, file: path.relative(ROOT, routeTs) })
      if (await exists(routeTsx)) res.push({ type: isApi ? "api" : "route", route: `/${routePath}`, file: path.relative(ROOT, routeTsx) })

      res.push(...await collectRoutes(full, path.posix.join(base, e.name)))
    }
  }
  return res
}

async function main() {
  if (!(await exists(APP_DIR))) {
    console.error("app directory not found")
    process.exit(1)
  }
  const routes = await collectRoutes(APP_DIR)
  routes.sort((a, b) => a.route.localeCompare(b.route))

  const lines: string[] = []
  lines.push("# Route Map")
  lines.push("")
  lines.push("Auto-generated by scripts/generate-route-map.ts")
  lines.push("")
  lines.push("| Type | Route | File |")
  lines.push("|------|-------|------|")
  for (const r of routes) {
    lines.push(`| ${r.type} | ${r.route} | ${r.file} |`)
  }

  await fs.writeFile(OUTPUT, lines.join("\n"), "utf8")
  console.log(`Wrote ${OUTPUT} (${routes.length} entries)`) // eslint-disable-line no-console
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
